name: Michael Bates
description: Web and iOS programming with passion and precision.
url: http://mklbtz.com
markdown: redcarpet
redcarpet:
  syntax_highlighter: rouge
exclude: ["Gemfile", "Gemfile.lock", "README.md", "CNAME"]
paginate: 5
